ALTER TABLE "CompanySettings"
ADD COLUMN "smtpHost" TEXT NOT NULL DEFAULT '',
ADD COLUMN "smtpPort" INTEGER NOT NULL DEFAULT 587,
ADD COLUMN "smtpSecurity" TEXT NOT NULL DEFAULT 'STARTTLS',
ADD COLUMN "smtpUser" TEXT NOT NULL DEFAULT '',
ADD COLUMN "smtpPasswordEncrypted" TEXT NOT NULL DEFAULT '',
ADD COLUMN "smtpFrom" TEXT NOT NULL DEFAULT '';
